# Generated by Django 3.0.8 on 2020-08-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dated', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('short', 'Short Term'), ('long', 'Long Term')], max_length=5)),
                ('salary', models.FloatField()),
                ('position_type', models.CharField(max_length=100)),
                ('job_category', models.CharField(max_length=100)),
                ('position_title', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('preferred_contact_method', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'personnel',
            },
        ),
    ]
