# Generated by Django 3.0.8 on 2020-08-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.CharField(choices=[('temp', 'Temp'), ('perm', 'Perm')], max_length=5),
        ),
    ]
