# Generated by Django 3.0.8 on 2020-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_type',
            field=models.CharField(default='dfgsdfg', max_length=120),
            preserve_default=False,
        ),
    ]
