# Generated by Django 3.0.8 on 2020-07-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200728_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='employment_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
