# Generated by Django 3.0.8 on 2020-08-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200803_1542'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover_Letter',
        ),
    ]
