# Generated by Django 3.0.8 on 2020-08-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_document_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_cv',
            name='document',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
